#!/bin/sh
#SBATCH --mem_bind=verbose,local
#SBATCH --cpu_bind=verbose,rank_ldom
#SBATCH --job-name=Mk1_Simple
#SBATCH --output=slurm.out
#SBATCH --error=slurm.err
#SBATCH --partition=x
#SBATCH --time=100:00:00
#SBATCH --cpus-per-task=6
#SBATCH --ntasks=8

srun mcnp5.mpi i=inp2 o=outp mc=mctal runtpe=runtpe
